version: '3'

services:
  gcc:
    build: . 
    user: root
    platform: linux/amd64
    tty: true
    working_dir: /lib/sample-proccess-trace
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./lib:/lib/sample-proccess-trace
